TirottaTech/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TirottaTech.Data;
using TirottaTech.Models;

namespace TirottaTech.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> userManager;

        private ApplicationUser currentUser;

        public CartController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            this.db = db;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            this.currentUser = await this.userManager.GetUserAsync(this.User);
            var cart = this.db.CartItems.Include(x => x.Product).Where(c => c.UserId == currentUser.Id).ToList();
            return View(cart);
        }
        public async Task<IActionResult> Add(int id)
        {
            this.currentUser = await this.userManager.GetUserAsync(this.User);
            //find product by id
            var product = this.db.Products.Find(id);
            //check if product already exists in the cart
            //var cartItem = this.db.CartItems.FirstOrDefault(c => c.ProductId == id);
            var cartItem = this.db.CartItems.FirstOrDefault(c => c.ProductId == id && c.UserId == currentUser.Id);
            //this.appUser.CartItems.FirstOrDefault()
            if (cartItem != null)
            {
                cartItem.Quantity++;
            }
            else
            {
                var item = new CartItem { ProductId = id, Product = product, Quantity = 1, UserId = currentUser.Id, User = currentUser };
                //add cartitem to db
                this.db.CartItems.Add(item);
            }
            await this.db.SaveChangesAsync();

            var cart = this.db.CartItems.Include(x => x.Product).Where(c => c.UserId == currentUser.Id).ToList();
            return View("Index", cart);
        }
        public async Task<IActionResult> Remove(int id)
        {
            this.currentUser = await this.userManager.GetUserAsync(this.User);
            //get product by id
            var product = this.db.CartItems.Include(x=>x.Product).FirstOrDefault(p => p.ProductId == id);
            if (product != null)
            {
                product.Quantity--;
                if (product.Quantity == 0)
                {
                    this.db.CartItems.Remove(product);
                }
                await this.db.SaveChangesAsync();
                var cart = this.db.CartItems.Include(x => x.Product).Where(c => c.UserId == currentUser.Id).ToList();
                return View("Index", cart);
            }
            else
            {
                return Content("Remove Action Failed. Product not found");
            }
            //remove from cart
            //save
        
        }
    }
}

TirottaTech/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TirottaTech.Data;
using TirottaTech.Models;
using TirottaTech.Services;

namespace TirottaTech.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly ICategoriesService categoriesService;

        public ProductsController(ApplicationDbContext _db, ICategoriesService categoriesService)
        {
            db = _db;
            this.categoriesService = categoriesService;
        }
        public IActionResult Index()
        {
            var products = this.db.Products.ToList();
            return View(products);
        }
        public IActionResult Get(int id)
        {
            var p = this.db.Products.Find(id);
            return View(p);
        }
        public IActionResult Filter(Dictionary<string, string> filters)
        {
            var products = this.db.Products.ToList();
            //var products = new List<Product>();
            string brandFilter = filters["brand"];
            
            //Base case
            if (brandFilter != "none")
            {
                products = this.db.Products.Where(x => x.Brand == brandFilter).ToList();
            }
            string sortFilter = filters["sort"];
            if (sortFilter == "lowtohigh")
            {
                products = products.OrderBy(x => x.Price).ToList();
            }
            else if (sortFilter == "hightolow")
            {
                products = products.OrderByDescending(x => x.Price).ToList();
            }
            else if (sortFilter == "az")
            {
                products = products.OrderBy(x => x.Name).ToList();
            }
            else if (sortFilter == "za")
            {
                products = products.OrderByDescending(x => x.Name).ToList();
            }
            return PartialView("_ProductsPartial", products);
        }
        //[HttpGet]
        //public IActionResult Add()
        //{
        //    var categoryProduct = new ProductInputModel();
        //    categoryProduct.CategoryItems = categoriesService.GetAllCategories();
        //    return View(categoryProduct);
        //}
        //[HttpPost]
        //public async Task<IActionResult> Add(ProductInputModel product)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View();
        //    }
        //    var p = new Product
        //    {
        //        Name = product.Name,
        //        Description = product.Description,
        //        Price = product.Price,
        //        ImageUrl = product.ImageUrl
        //    };

        //    this.db.Products.Add(p);
        //    await this.db.SaveChangesAsync();

        //    var products = this.db.Products.ToList();
        //    return View(products);
        //}
    }
}

TirottaTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TirottaTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=DotGothic16&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow" style = "background: rgb(229, 152, 155)">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tirotta Tech</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Store</a>
                        </li>
                        @if (this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div >
        <main role="main" >
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; TirottaTech 2021.All Rights Reserved
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>